### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by voodoologic** [alsemyonov/ember-faye#1]
Dougs-Mackbook > ~/digest(master) $ember-v
(node:16694) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
WARNING: WARNING: Node v6.2.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.5.1
node: 6.2.0
os: darwin x64
ember install ember-faye

Dougs-Mackbook > ~/digest(master) $ember install ember-faye
(node:16703) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
WARNING: WARNING: Node v6.2.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
installing ember-faye
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by pawangiri** [comment]
I am getting similar error - any update on PR above ?

The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.

ember-cli: 2.5.0
node: 4.2.0
os: darwin x64

> Installed packages for tooling via npm.
> installing ember-faye
> The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by cyril-sf** [comment]
I opened #3 to fix this problem.
